"""add api key rate limit

Revision ID: 2b4ac0a85a44
Revises: bfd85ac87d16
Create Date: 2026-08-12 18:28:12.183358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4ac0a85a44'
down_revision: Union[str, Sequence[str], None] = 'bfd85ac87d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('rate_limit_per_minute', sa.Integer(), server_default='60', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'rate_limit_per_minute')
    # ### end Alembic commands ###
