"""create request usage table

Revision ID: bfd85ac87d16
Revises: a15a9066fbb7
Create Date: 2026-08-12 11:19:37.423861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd85ac87d16'
down_revision: Union[str, Sequence[str], None] = 'a15a9066fbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_usage_api_key_id'), 'request_usage', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_request_usage_request_id'), 'request_usage', ['request_id'], unique=True)
    op.create_index(op.f('ix_request_usage_task'), 'request_usage', ['task'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_usage_task'), table_name='request_usage')
    op.drop_index(op.f('ix_request_usage_request_id'), table_name='request_usage')
    op.drop_index(op.f('ix_request_usage_api_key_id'), table_name='request_usage')
    op.drop_table('request_usage')
    # ### end Alembic commands ###
